-- Supabase schema + RLS + recommended RPC functions
-- Run this entire script in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- ===== Tables =====

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text not null default '',
  address text not null default '',
  promo_email_opt_in boolean not null default false,
  promo_email_opt_in_at timestamptz,
  account_type text not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists account_type text not null default 'customer';

alter table public.profiles
  add column if not exists promo_email_opt_in boolean not null default false;

alter table public.profiles
  add column if not exists promo_email_opt_in_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_account_type_check'
  ) then
    alter table public.profiles
      add constraint profiles_account_type_check
      check (
        account_type in (
          'customer',
          'support_agent',
          'rider',
          'delivery',
          'cashier',
          'admin',
          'super_admin'
        )
      );
  end if;
end $$;

alter table public.profiles
  drop constraint if exists profiles_account_type_check;

alter table public.profiles
  add constraint profiles_account_type_check
  check (
    account_type in (
      'customer',
      'support_agent',
      'rider',
      'delivery',
      'cashier',
      'admin',
      'super_admin'
    )
  );

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price numeric(10, 2) not null default 0,
  image_url text not null default '',
  description text not null default '',
  category text not null default 'All',
  created_at timestamptz not null default now()
);

create table if not exists public.product_variant_stocks (
  product_id uuid not null references public.products(id) on delete cascade,
  size text not null,
  color text not null,
  stock int not null default 0 check (stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, size, color)
);

insert into public.product_variant_stocks (product_id, size, color, stock)
select
  p.id,
  sizes.size,
  colors.color,
  20
from public.products p
cross join (values ('S'), ('M'), ('L'), ('XL')) as sizes(size)
cross join (values ('Black'), ('White'), ('Blue'), ('Red')) as colors(color)
on conflict (product_id, size, color) do nothing;

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cart_key text not null,
  product_id text not null,
  name text not null,
  price numeric(10, 2) not null,
  image_url text not null default '',
  qty int not null default 1 check (qty > 0),
  size text,
  color text,
  created_at timestamptz not null default now(),
  unique (user_id, cart_key)
);

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subtotal numeric(10, 2) not null default 0,
  discount_amount numeric(10, 2) not null default 0,
  vat_amount numeric(10, 2) not null default 0,
  promo_code text not null default '',
  total numeric(10, 2) not null default 0,
  address text not null default '',
  address_details text not null default '',
  delivery_type text not null default 'drop_off',
  payment_method text not null default 'cash_on_delivery',
  cash_paid_confirmed boolean not null default false,
  cash_paid_confirmed_at timestamptz,
  cash_paid_confirmed_by uuid references auth.users(id) on delete set null,
  payment_reference text not null default '',
  delivery_latitude double precision,
  delivery_longitude double precision,
  delivery_location_updated_at timestamptz,
  delivery_location_updated_by uuid references auth.users(id) on delete set null,
  delivery_location_note text not null default '',
  status text not null default 'order_received',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.product_ratings (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  rating int not null check (rating between 1 and 5),
  review text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 95),
  min_order_total numeric(10, 2) not null default 0 check (min_order_total >= 0),
  is_active boolean not null default true,
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payway_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  provider text not null default 'payway',
  tran_id text not null,
  amount numeric(10, 2) not null default 0,
  currency text not null default 'USD',
  payment_status text not null default '',
  payment_status_code int,
  gateway_status_code text not null default '',
  gateway_message text not null default '',
  raw_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, tran_id)
);

alter table public.payway_transactions
  add column if not exists user_id uuid not null references auth.users(id) on delete cascade;

alter table public.payway_transactions
  add column if not exists order_id bigint references public.orders(id) on delete set null;

alter table public.payway_transactions
  add column if not exists provider text not null default 'payway';

alter table public.payway_transactions
  add column if not exists tran_id text not null;

alter table public.payway_transactions
  add column if not exists amount numeric(10, 2) not null default 0;

alter table public.payway_transactions
  add column if not exists currency text not null default 'USD';

alter table public.payway_transactions
  add column if not exists payment_status text not null default '';

alter table public.payway_transactions
  add column if not exists payment_status_code int;

alter table public.payway_transactions
  add column if not exists gateway_status_code text not null default '';

alter table public.payway_transactions
  add column if not exists gateway_message text not null default '';

alter table public.payway_transactions
  add column if not exists raw_response jsonb not null default '{}'::jsonb;

alter table public.payway_transactions
  add column if not exists created_at timestamptz not null default now();

alter table public.payway_transactions
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'payway_transactions_provider_tran_key'
  ) then
    alter table public.payway_transactions
      add constraint payway_transactions_provider_tran_key
      unique (provider, tran_id);
  end if;
end $$;

alter table public.orders
  add column if not exists subtotal numeric(10, 2) not null default 0;

alter table public.orders
  add column if not exists discount_amount numeric(10, 2) not null default 0;

alter table public.orders
  add column if not exists vat_amount numeric(10, 2) not null default 0;

alter table public.orders
  add column if not exists promo_code text not null default '';

alter table public.orders
  add column if not exists address_details text not null default '';

alter table public.orders
  add column if not exists delivery_type text not null default 'drop_off';

alter table public.orders
  add column if not exists payment_method text not null default 'cash_on_delivery';

alter table public.orders
  add column if not exists cash_paid_confirmed boolean not null default false;

alter table public.orders
  add column if not exists cash_paid_confirmed_at timestamptz;

alter table public.orders
  add column if not exists cash_paid_confirmed_by uuid references auth.users(id) on delete set null;

alter table public.orders
  add column if not exists payment_reference text not null default '';

alter table public.orders
  add column if not exists delivery_latitude double precision;

alter table public.orders
  add column if not exists delivery_longitude double precision;

alter table public.orders
  add column if not exists delivery_location_updated_at timestamptz;

alter table public.orders
  add column if not exists delivery_location_updated_by uuid references auth.users(id) on delete set null;

alter table public.orders
  add column if not exists delivery_location_note text not null default '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_delivery_latitude_check'
  ) then
    alter table public.orders
      add constraint orders_delivery_latitude_check
      check (
        delivery_latitude is null
        or (delivery_latitude >= -90 and delivery_latitude <= 90)
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_delivery_longitude_check'
  ) then
    alter table public.orders
      add constraint orders_delivery_longitude_check
      check (
        delivery_longitude is null
        or (delivery_longitude >= -180 and delivery_longitude <= 180)
      );
  end if;
end $$;

alter table public.promo_codes
  add column if not exists discount_percent numeric(5, 2) not null default 0;

alter table public.promo_codes
  add column if not exists min_order_total numeric(10, 2) not null default 0;

alter table public.promo_codes
  add column if not exists is_active boolean not null default true;

alter table public.promo_codes
  add column if not exists starts_at timestamptz;

alter table public.promo_codes
  add column if not exists expires_at timestamptz;

alter table public.promo_codes
  add column if not exists created_at timestamptz not null default now();

alter table public.promo_codes
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subtitle text not null default '',
  badge text not null default '',
  is_active boolean not null default false,
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  theme text not null default 'default',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.events
  add column if not exists starts_at timestamptz not null default now();

alter table public.events
  add column if not exists expires_at timestamptz not null default (now() + interval '24 hours');

alter table public.events
  add column if not exists theme text not null default 'default';

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'events_time_window_check'
  ) then
    alter table public.events
      drop constraint events_time_window_check;
  end if;
end $$;

alter table public.events
  add constraint events_time_window_check
  check (expires_at > starts_at);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'events_theme_check'
  ) then
    alter table public.events
      drop constraint events_theme_check;
  end if;
end $$;

alter table public.events
  add constraint events_theme_check
  check (
    theme in (
      'default',
      'christmas_sale',
      'valentine',
      'new_year',
      'black_friday',
      'summer_sale'
    )
  );

create table if not exists public.app_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info',
  feature text not null,
  action text not null,
  message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'app_logs_level_check'
  ) then
    alter table public.app_logs
      add constraint app_logs_level_check
      check (level in ('info', 'warning', 'error'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'payway_transactions_provider_check'
  ) then
    alter table public.payway_transactions
      add constraint payway_transactions_provider_check
      check (provider in ('payway'));
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'orders_status_check'
  ) then
    alter table public.orders
      drop constraint orders_status_check;
  end if;
end $$;

alter table public.orders
  add constraint orders_status_check
  check (
    status in (
      'order_received',
      'order_packed',
      'ready_for_pickup',
      'out_for_delivery',
      'delivered',
      'cancelled',
      -- Legacy statuses kept for compatibility during transition
      'pending',
      'paid',
      'shipped'
    )
  );

alter table public.orders
  alter column status set default 'order_received';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_payment_method_check'
  ) then
    alter table public.orders
      add constraint orders_payment_method_check
      check (payment_method in ('cash_on_delivery', 'aba_payway_qr'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_delivery_type_check'
  ) then
    alter table public.orders
      add constraint orders_delivery_type_check
      check (delivery_type in ('drop_off', 'real_meeting'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_discount_amount_check'
  ) then
    alter table public.orders
      add constraint orders_discount_amount_check
      check (discount_amount >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_vat_amount_check'
  ) then
    alter table public.orders
      add constraint orders_vat_amount_check
      check (vat_amount >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_subtotal_check'
  ) then
    alter table public.orders
      add constraint orders_subtotal_check
      check (subtotal >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_total_check'
  ) then
    alter table public.orders
      add constraint orders_total_check
      check (total >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'promo_codes_code_not_blank'
  ) then
    alter table public.promo_codes
      add constraint promo_codes_code_not_blank
      check (length(trim(code)) > 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'promo_codes_discount_percent_check'
  ) then
    alter table public.promo_codes
      add constraint promo_codes_discount_percent_check
      check (discount_percent >= 0 and discount_percent <= 95);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'promo_codes_min_order_total_check'
  ) then
    alter table public.promo_codes
      add constraint promo_codes_min_order_total_check
      check (min_order_total >= 0);
  end if;
end $$;

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_cart_items_user on public.cart_items(user_id);
create index if not exists idx_wishlist_items_user on public.wishlist_items(user_id);
create index if not exists idx_orders_user_created on public.orders(user_id, created_at desc);
create index if not exists idx_orders_delivery_location_updated on public.orders(delivery_location_updated_at desc);
create index if not exists idx_orders_delivery_location_updated_by on public.orders(delivery_location_updated_by);
create index if not exists idx_payway_transactions_user_created on public.payway_transactions(user_id, created_at desc);
create index if not exists idx_payway_transactions_order_id on public.payway_transactions(order_id);
create index if not exists idx_profiles_account_type on public.profiles(account_type);
create index if not exists idx_events_active_created on public.events(is_active, created_at desc);
create index if not exists idx_events_active_window on public.events(is_active, starts_at, expires_at);
create index if not exists idx_events_expires_at on public.events(expires_at);
create index if not exists idx_events_theme on public.events(theme);
create unique index if not exists uq_promo_codes_code_upper on public.promo_codes(upper(trim(code)));
create index if not exists idx_promo_codes_active_window on public.promo_codes(is_active, starts_at, expires_at);
create index if not exists idx_variant_stocks_product on public.product_variant_stocks(product_id);
create index if not exists idx_product_ratings_product on public.product_ratings(product_id);
create index if not exists idx_app_logs_created_at on public.app_logs(created_at desc);
create index if not exists idx_app_logs_feature on public.app_logs(feature);

-- ===== Utility Trigger Functions =====

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_events_set_updated_at on public.events;
create trigger trg_events_set_updated_at
before update on public.events
for each row
execute function public.set_updated_at();

drop trigger if exists trg_promo_codes_set_updated_at on public.promo_codes;
create trigger trg_promo_codes_set_updated_at
before update on public.promo_codes
for each row
execute function public.set_updated_at();

drop trigger if exists trg_variant_stocks_set_updated_at on public.product_variant_stocks;
create trigger trg_variant_stocks_set_updated_at
before update on public.product_variant_stocks
for each row
execute function public.set_updated_at();

drop trigger if exists trg_product_ratings_set_updated_at on public.product_ratings;
create trigger trg_product_ratings_set_updated_at
before update on public.product_ratings
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.is_super_admin(
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = coalesce(p_user_id, auth.uid())
      and p.account_type = 'super_admin'
  );
$$;

create or replace function public.is_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = coalesce(p_user_id, auth.uid())
      and p.account_type in ('admin', 'super_admin')
  );
$$;

create or replace function public.is_cashier(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = coalesce(p_user_id, auth.uid())
      and p.account_type = 'cashier'
  );
$$;

create or replace function public.is_support_agent(
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = coalesce(p_user_id, auth.uid())
      and p.account_type = 'support_agent'
  );
$$;

create or replace function public.is_rider(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = coalesce(p_user_id, auth.uid())
      and p.account_type in ('rider', 'delivery')
  );
$$;

create or replace function public.is_staff(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin(coalesce(p_user_id, auth.uid()))
    or public.is_cashier(coalesce(p_user_id, auth.uid()))
    or public.is_support_agent(coalesce(p_user_id, auth.uid()))
    or public.is_rider(coalesce(p_user_id, auth.uid()));
$$;

create or replace function public.guard_profile_account_type_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.account_type is distinct from old.account_type then
    if auth.uid() is not null and not public.is_super_admin(auth.uid()) then
      raise exception 'Only super admins can change account type';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_guard_account_type on public.profiles;
create trigger trg_profiles_guard_account_type
before update on public.profiles
for each row
execute function public.guard_profile_account_type_change();

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-images',
  'product-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp']
)
on conflict (id) do update
  set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read"
  on storage.objects
  for select
  to public
  using (bucket_id = 'product-images');

drop policy if exists "product_images_admin_insert" on storage.objects;
create policy "product_images_admin_insert"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'product-images'
    and public.is_admin(auth.uid())
  );

drop policy if exists "product_images_admin_update" on storage.objects;
create policy "product_images_admin_update"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'product-images'
    and public.is_admin(auth.uid())
  )
  with check (
    bucket_id = 'product-images'
    and public.is_admin(auth.uid())
  );

drop policy if exists "product_images_admin_delete" on storage.objects;
create policy "product_images_admin_delete"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'product-images'
    and public.is_admin(auth.uid())
  );

create or replace function public.has_purchased_product(
  p_user_id uuid,
  p_product_id text
)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select
    p_user_id is not null
    and nullif(trim(coalesce(p_product_id, '')), '') is not null
    and exists (
      select 1
      from public.orders o
      cross join lateral jsonb_array_elements(
        coalesce(o.items, '[]'::jsonb)
      ) as item
      where o.user_id = p_user_id
        and coalesce(lower(trim(o.status)), '') <> 'cancelled'
        and coalesce(
          item.value->>'productId',
          item.value->>'product_id',
          ''
        ) = trim(p_product_id)
    );
$$;

create or replace function public.rpc_list_best_seller_product_ids(
  p_days int default 30,
  p_limit int default 5
)
returns table (product_id text)
language sql
stable
security definer
set search_path = public
as $$
  with sales as (
    select
      nullif(
        trim(
          coalesce(
            item.value->>'productId',
            item.value->>'product_id',
            ''
          )
        ),
        ''
      ) as product_id,
      case
        when coalesce(item.value->>'qty', item.value->>'quantity', '') ~ '^\s*\d+\s*$'
          then greatest(
            trim(coalesce(item.value->>'qty', item.value->>'quantity'))::int,
            1
          )
        else 1
      end as qty
    from public.orders o
    cross join lateral jsonb_array_elements(coalesce(o.items, '[]'::jsonb)) as item
    where coalesce(lower(trim(o.status)), '') <> 'cancelled'
      and o.created_at >=
        now() - make_interval(days => greatest(coalesce(p_days, 30), 1))
  )
  select s.product_id
  from sales s
  where s.product_id is not null
  group by s.product_id
  order by sum(s.qty) desc, s.product_id asc
  limit greatest(coalesce(p_limit, 5), 1);
$$;

-- ===== RLS =====

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_variant_stocks enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.orders enable row level security;
alter table public.product_ratings enable row level security;
alter table public.payway_transactions enable row level security;
alter table public.events enable row level security;
alter table public.promo_codes enable row level security;
alter table public.app_logs enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "profiles_delete_own" on public.profiles;
create policy "profiles_delete_own"
  on public.profiles
  for delete
  using (auth.uid() = id);

drop policy if exists "products_read_all" on public.products;
create policy "products_read_all"
  on public.products
  for select
  to anon, authenticated
  using (true);

drop policy if exists "variant_stocks_read_all" on public.product_variant_stocks;
create policy "variant_stocks_read_all"
  on public.product_variant_stocks
  for select
  to anon, authenticated
  using (true);

drop policy if exists "cart_select_own" on public.cart_items;
create policy "cart_select_own"
  on public.cart_items
  for select
  using (auth.uid() = user_id);

drop policy if exists "cart_insert_own" on public.cart_items;
create policy "cart_insert_own"
  on public.cart_items
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "cart_update_own" on public.cart_items;
create policy "cart_update_own"
  on public.cart_items
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "cart_delete_own" on public.cart_items;
create policy "cart_delete_own"
  on public.cart_items
  for delete
  using (auth.uid() = user_id);

drop policy if exists "wishlist_select_own" on public.wishlist_items;
create policy "wishlist_select_own"
  on public.wishlist_items
  for select
  using (auth.uid() = user_id);

drop policy if exists "wishlist_insert_own" on public.wishlist_items;
create policy "wishlist_insert_own"
  on public.wishlist_items
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "wishlist_delete_own" on public.wishlist_items;
create policy "wishlist_delete_own"
  on public.wishlist_items
  for delete
  using (auth.uid() = user_id);

drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own"
  on public.orders
  for select
  using (auth.uid() = user_id);

drop policy if exists "orders_insert_own" on public.orders;
create policy "orders_insert_own"
  on public.orders
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "product_ratings_read_all" on public.product_ratings;
create policy "product_ratings_read_all"
  on public.product_ratings
  for select
  to anon, authenticated
  using (true);

drop policy if exists "product_ratings_insert_after_purchase" on public.product_ratings;
create policy "product_ratings_insert_after_purchase"
  on public.product_ratings
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and public.has_purchased_product(auth.uid(), product_id)
  );

drop policy if exists "product_ratings_update_after_purchase" on public.product_ratings;
create policy "product_ratings_update_after_purchase"
  on public.product_ratings
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and public.has_purchased_product(auth.uid(), product_id)
  );

drop policy if exists "product_ratings_delete_own" on public.product_ratings;
create policy "product_ratings_delete_own"
  on public.product_ratings
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "payway_transactions_select_own" on public.payway_transactions;
create policy "payway_transactions_select_own"
  on public.payway_transactions
  for select
  using (auth.uid() = user_id);

drop policy if exists "payway_transactions_insert_own" on public.payway_transactions;
create policy "payway_transactions_insert_own"
  on public.payway_transactions
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "payway_transactions_update_own" on public.payway_transactions;
create policy "payway_transactions_update_own"
  on public.payway_transactions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "payway_transactions_select_admin" on public.payway_transactions;
create policy "payway_transactions_select_admin"
  on public.payway_transactions
  for select
  to authenticated
  using (public.is_admin(auth.uid()));

drop policy if exists "events_read_all" on public.events;
create policy "events_read_all"
  on public.events
  for select
  to anon, authenticated
  using (true);

drop policy if exists "promo_codes_admin_all" on public.promo_codes;
create policy "promo_codes_admin_all"
  on public.promo_codes
  for all
  to authenticated
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

drop policy if exists "app_logs_insert_any" on public.app_logs;
create policy "app_logs_insert_any"
  on public.app_logs
  for insert
  to anon, authenticated
  with check (
    user_id is null
    or auth.uid() = user_id
  );

drop policy if exists "app_logs_select_admin" on public.app_logs;
create policy "app_logs_select_admin"
  on public.app_logs
  for select
  to authenticated
  using (public.is_admin(auth.uid()));

-- ===== Recommended Functions (RPC) =====

create or replace function public.make_cart_key(
  p_product_id text,
  p_size text default null,
  p_color text default null
)
returns text
language sql
immutable
set search_path = public
as $$
  select case
    when coalesce(trim(p_size), '') = '' and coalesce(trim(p_color), '') = ''
      then p_product_id
    else p_product_id || '_' || coalesce(trim(p_size), '') || '_' || coalesce(trim(p_color), '')
  end;
$$;

create or replace function public.seed_default_product_variant_stocks(
  p_product_id uuid,
  p_default_stock int default 20
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.product_variant_stocks (product_id, size, color, stock)
  select
    p_product_id,
    sizes.size,
    colors.color,
    greatest(coalesce(p_default_stock, 0), 0)
  from (values ('S'), ('M'), ('L'), ('XL')) as sizes(size)
  cross join (values ('Black'), ('White'), ('Blue'), ('Red')) as colors(color)
  on conflict (product_id, size, color) do nothing;
end;
$$;

create or replace function public.rpc_get_product_variant_stocks(
  p_product_id uuid
)
returns table (
  size text,
  color text,
  stock int
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    s.size,
    s.color,
    s.stock
  from public.product_variant_stocks s
  where s.product_id = p_product_id
  order by s.size, s.color;
$$;

drop function if exists public.rpc_upsert_profile(text, text, text);
create or replace function public.rpc_upsert_profile(
  p_name text default '',
  p_phone text default '',
  p_address text default '',
  p_promo_email_opt_in boolean default null
)
returns public.profiles
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.profiles;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  insert into public.profiles (
    id,
    name,
    phone,
    address,
    promo_email_opt_in,
    promo_email_opt_in_at
  )
  values (
    v_user,
    coalesce(p_name, ''),
    coalesce(p_phone, ''),
    coalesce(p_address, ''),
    coalesce(p_promo_email_opt_in, false),
    case when coalesce(p_promo_email_opt_in, false) then now() else null end
  )
  on conflict (id) do update
    set name = excluded.name,
        phone = excluded.phone,
        address = excluded.address,
        promo_email_opt_in = coalesce(
          p_promo_email_opt_in,
          public.profiles.promo_email_opt_in
        ),
        promo_email_opt_in_at = case
          when p_promo_email_opt_in is true and
            coalesce(public.profiles.promo_email_opt_in, false) = false
            then now()
          when p_promo_email_opt_in is false then null
          else public.profiles.promo_email_opt_in_at
        end
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.rpc_get_profile()
returns public.profiles
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.profiles;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  select *
  into v_row
  from public.profiles
  where id = v_user;

  if v_row.id is null then
    insert into public.profiles (id)
    values (v_user)
    returning * into v_row;
  end if;

  return v_row;
end;
$$;

create or replace function public.rpc_list_products(
  p_query text default '',
  p_category text default 'All'
)
returns setof public.products
language sql
stable
security invoker
set search_path = public
as $$
  select p.*
  from public.products p
  where (
    coalesce(trim(p_query), '') = ''
    or lower(p.name) like '%' || lower(trim(p_query)) || '%'
  )
  and (
    coalesce(trim(p_category), '') = ''
    or lower(trim(p_category)) = 'all'
    or lower(p.category) = lower(trim(p_category))
  )
  order by p.created_at desc;
$$;

create or replace function public.rpc_get_cart_items()
returns setof public.cart_items
language sql
stable
security invoker
set search_path = public
as $$
  select c.*
  from public.cart_items c
  where c.user_id = auth.uid()
  order by c.created_at desc;
$$;

create or replace function public.rpc_get_wishlist_ids()
returns table (product_id text)
language sql
stable
security invoker
set search_path = public
as $$
  select w.product_id
  from public.wishlist_items w
  where w.user_id = auth.uid()
  order by w.created_at desc;
$$;

create or replace function public.rpc_add_to_cart(
  p_product_id text,
  p_name text,
  p_price numeric,
  p_image_url text default '',
  p_size text default null,
  p_color text default null,
  p_qty int default 1
)
returns public.cart_items
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_qty int := greatest(coalesce(p_qty, 1), 1);
  v_size text := coalesce(nullif(trim(coalesce(p_size, '')), ''), '');
  v_color text := coalesce(nullif(trim(coalesce(p_color, '')), ''), '');
  v_cart_key text := public.make_cart_key(p_product_id, v_size, v_color);
  v_product_uuid uuid := p_product_id::uuid;
  v_stock int;
  v_existing_qty int := 0;
  v_row public.cart_items;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  select s.stock
  into v_stock
  from public.product_variant_stocks s
  where s.product_id = v_product_uuid
    and s.size = v_size
    and s.color = v_color
  for update;

  if found then
    if v_stock <= 0 then
      raise exception 'Out of stock';
    end if;

    select coalesce(c.qty, 0)
    into v_existing_qty
    from public.cart_items c
    where c.user_id = v_user and c.cart_key = v_cart_key;

    if v_existing_qty + v_qty > v_stock then
      raise exception 'Only % item(s) available for this size/color', v_stock;
    end if;
  end if;

  insert into public.cart_items (
    user_id, cart_key, product_id, name, price, image_url, qty, size, color
  )
  values (
    v_user,
    v_cart_key,
    p_product_id,
    p_name,
    p_price,
    coalesce(p_image_url, ''),
    v_qty,
    nullif(v_size, ''),
    nullif(v_color, '')
  )
  on conflict (user_id, cart_key) do update
    set qty = public.cart_items.qty + excluded.qty,
        name = excluded.name,
        price = excluded.price,
        image_url = excluded.image_url,
        size = excluded.size,
        color = excluded.color
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.rpc_set_cart_qty(
  p_cart_key text,
  p_qty int
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_product_id text;
  v_size text := '';
  v_color text := '';
  v_stock int;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(p_qty, 0) <= 0 then
    delete from public.cart_items
    where user_id = v_user and cart_key = p_cart_key;
  else
    select
      c.product_id,
      coalesce(c.size, ''),
      coalesce(c.color, '')
    into v_product_id, v_size, v_color
    from public.cart_items c
    where c.user_id = v_user and c.cart_key = p_cart_key;

    if v_product_id is not null then
      select s.stock
      into v_stock
      from public.product_variant_stocks s
      where s.product_id = v_product_id::uuid
        and s.size = v_size
        and s.color = v_color;

      if found and p_qty > v_stock then
        raise exception 'Only % item(s) available for this size/color', v_stock;
      end if;
    end if;

    update public.cart_items
    set qty = p_qty
    where user_id = v_user and cart_key = p_cart_key;
  end if;
end;
$$;

create or replace function public.rpc_clear_cart()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_deleted integer := 0;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  delete from public.cart_items where user_id = v_user;
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

create or replace function public.rpc_toggle_wishlist(
  p_product_id text
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if exists (
    select 1
    from public.wishlist_items
    where user_id = v_user and product_id = p_product_id
  ) then
    delete from public.wishlist_items
    where user_id = v_user and product_id = p_product_id;
    return false;
  else
    insert into public.wishlist_items (user_id, product_id)
    values (v_user, p_product_id)
    on conflict (user_id, product_id) do nothing;
    return true;
  end if;
end;
$$;

create or replace function public.rpc_cart_total()
returns numeric
language sql
security invoker
set search_path = public
as $$
  select coalesce(sum(price * qty), 0)
  from public.cart_items
  where user_id = auth.uid();
$$;

drop function if exists public.rpc_place_order(text, text, text, text);
drop function if exists public.rpc_place_order(text, text, text, text, text, text);
drop function if exists public.rpc_place_order(text, text, text, text, text, text, text);

create or replace function public.rpc_validate_promo_code(
  p_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_code text := upper(trim(coalesce(p_code, '')));
  v_subtotal numeric(10, 2) := 0;
  v_discount_percent numeric(5, 2) := 0;
  v_discount_amount numeric(10, 2) := 0;
  v_total numeric(10, 2) := 0;
  v_min_total numeric(10, 2) := 0;
begin
  if v_user is null then
    return jsonb_build_object(
      'valid', false,
      'message', 'Not authenticated',
      'code', '',
      'discount_percent', 0,
      'discount_amount', 0,
      'subtotal', 0,
      'total', 0,
      'min_order_total', 0
    );
  end if;

  select coalesce(sum(c.price * c.qty), 0)
  into v_subtotal
  from public.cart_items c
  where c.user_id = v_user;

  if v_code = '' then
    return jsonb_build_object(
      'valid', false,
      'message', 'Promo code is required',
      'code', '',
      'discount_percent', 0,
      'discount_amount', 0,
      'subtotal', v_subtotal,
      'total', v_subtotal,
      'min_order_total', 0
    );
  end if;

  select
    p.discount_percent,
    p.min_order_total
  into
    v_discount_percent,
    v_min_total
  from public.promo_codes p
  where upper(trim(p.code)) = v_code
    and p.is_active = true
    and (p.starts_at is null or p.starts_at <= now())
    and (p.expires_at is null or p.expires_at >= now())
  limit 1;

  if not found then
    return jsonb_build_object(
      'valid', false,
      'message', 'Promo code is invalid or expired',
      'code', v_code,
      'discount_percent', 0,
      'discount_amount', 0,
      'subtotal', v_subtotal,
      'total', v_subtotal,
      'min_order_total', 0
    );
  end if;

  if v_subtotal < coalesce(v_min_total, 0) then
    return jsonb_build_object(
      'valid', false,
      'message', format(
        'Promo code requires minimum order total of %s',
        to_char(v_min_total, 'FM999999990D00')
      ),
      'code', v_code,
      'discount_percent', v_discount_percent,
      'discount_amount', 0,
      'subtotal', v_subtotal,
      'total', v_subtotal,
      'min_order_total', v_min_total
    );
  end if;

  v_discount_amount := round(v_subtotal * (coalesce(v_discount_percent, 0) / 100.0), 2);
  v_discount_amount := greatest(0, least(v_discount_amount, v_subtotal));
  v_total := round(v_subtotal - v_discount_amount, 2);

  return jsonb_build_object(
    'valid', true,
    'message', 'Promo code applied',
    'code', v_code,
    'discount_percent', v_discount_percent,
    'discount_amount', v_discount_amount,
    'subtotal', v_subtotal,
    'total', v_total,
    'min_order_total', v_min_total
  );
end;
$$;

create or replace function public.rpc_place_order(
  p_address text default null,
  p_status text default 'order_received',
  p_delivery_type text default 'drop_off',
  p_address_details text default '',
  p_payment_method text default 'cash_on_delivery',
  p_payment_reference text default '',
  p_promo_code text default ''
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_items jsonb;
  v_subtotal numeric(10, 2);
  v_discount_amount numeric(10, 2) := 0;
  v_vat_amount numeric(10, 2) := 0;
  v_total numeric(10, 2);
  v_order_id bigint;
  v_address text;
  v_contact_phone text;
  v_address_details text := coalesce(trim(coalesce(p_address_details, '')), '');
  v_status text := coalesce(
    nullif(lower(trim(coalesce(p_status, ''))), ''),
    'order_received'
  );
  v_delivery_type text := coalesce(
    nullif(lower(trim(coalesce(p_delivery_type, ''))), ''),
    'drop_off'
  );
  v_payment_method text := coalesce(
    nullif(lower(trim(coalesce(p_payment_method, ''))), ''),
    'cash_on_delivery'
  );
  v_payment_reference text := coalesce(trim(coalesce(p_payment_reference, '')), '');
  v_promo_code text := upper(trim(coalesce(p_promo_code, '')));
  v_promo_discount_percent numeric(5, 2) := 0;
  v_promo_min_total numeric(10, 2) := 0;
  v_stock int;
  v_item record;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if v_delivery_type not in ('drop_off', 'real_meeting') then
    raise exception 'Invalid delivery_type';
  end if;

  if v_payment_method not in ('cash_on_delivery', 'aba_payway_qr') then
    raise exception 'Invalid payment_method';
  end if;

  if v_status in ('pending', 'paid') then
    v_status := 'order_received';
  elsif v_status = 'shipped' then
    v_status := 'out_for_delivery';
  end if;

  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'productId', product_id,
          'name', name,
          'price', price,
          'imageUrl', image_url,
          'qty', qty,
          'size', size,
          'color', color
        )
      ),
      '[]'::jsonb
    ),
    coalesce(sum(price * qty), 0)
  into v_items, v_subtotal
  from public.cart_items
  where user_id = v_user;

  if jsonb_array_length(v_items) = 0 then
    raise exception 'Cart is empty';
  end if;

  select nullif(trim(p.phone), '')
  into v_contact_phone
  from public.profiles p
  where p.id = v_user;

  if v_contact_phone is null then
    raise exception 'Phone number is required';
  end if;

  if v_promo_code <> '' then
    select
      p.discount_percent,
      p.min_order_total
    into
      v_promo_discount_percent,
      v_promo_min_total
    from public.promo_codes p
    where upper(trim(p.code)) = v_promo_code
      and p.is_active = true
      and (p.starts_at is null or p.starts_at <= now())
      and (p.expires_at is null or p.expires_at >= now())
    limit 1;

    if not found then
      raise exception 'Invalid or expired promo code';
    end if;

    if v_subtotal < coalesce(v_promo_min_total, 0) then
      raise exception
        'Promo code requires minimum order total of %',
        to_char(v_promo_min_total, 'FM999999990D00');
    end if;

    v_discount_amount := round(v_subtotal * (coalesce(v_promo_discount_percent, 0) / 100.0), 2);
  end if;

  v_discount_amount := greatest(0, least(v_discount_amount, v_subtotal));
  v_vat_amount := round((v_subtotal - v_discount_amount) * 0.10, 2);
  v_vat_amount := greatest(0, v_vat_amount);
  v_total := round(v_subtotal - v_discount_amount + v_vat_amount, 2);

  v_address := nullif(trim(coalesce(p_address, '')), '');
  if v_address is null then
    select nullif(trim(address), '')
    into v_address
    from public.profiles
    where id = v_user;
  end if;

  if v_address is null then
    raise exception 'Address is required';
  end if;

  for v_item in
    select
      c.product_id,
      coalesce(c.size, '') as size,
      coalesce(c.color, '') as color,
      c.qty
    from public.cart_items c
    where c.user_id = v_user
  loop
    select s.stock
    into v_stock
    from public.product_variant_stocks s
    where s.product_id = v_item.product_id::uuid
      and s.size = v_item.size
      and s.color = v_item.color
    for update;

    if found and v_stock < v_item.qty then
      raise exception
        'Insufficient stock for product %, size %, color %',
        v_item.product_id,
        nullif(v_item.size, ''),
        nullif(v_item.color, '');
    end if;
  end loop;

  insert into public.orders (
    user_id,
    subtotal,
    discount_amount,
    vat_amount,
    promo_code,
    total,
    address,
    address_details,
    delivery_type,
    payment_method,
    payment_reference,
    status,
    items
  )
  values (
    v_user,
    v_subtotal,
    v_discount_amount,
    v_vat_amount,
    v_promo_code,
    v_total,
    v_address,
    v_address_details,
    v_delivery_type,
    v_payment_method,
    v_payment_reference,
    v_status,
    v_items
  )
  returning id into v_order_id;

  for v_item in
    select
      c.product_id,
      coalesce(c.size, '') as size,
      coalesce(c.color, '') as color,
      c.qty
    from public.cart_items c
    where c.user_id = v_user
  loop
    update public.product_variant_stocks s
    set stock = s.stock - v_item.qty
    where s.product_id = v_item.product_id::uuid
      and s.size = v_item.size
      and s.color = v_item.color;
  end loop;

  delete from public.cart_items where user_id = v_user;

  return v_order_id;
end;
$$;

create or replace function public.rpc_get_orders()
returns setof public.orders
language sql
stable
security invoker
set search_path = public
as $$
  select o.*
  from public.orders o
  where o.user_id = auth.uid()
  order by o.created_at desc;
$$;

create or replace function public.rpc_admin_create_product(
  p_name text,
  p_price numeric,
  p_image_url text default '',
  p_description text default '',
  p_category text default 'All'
)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.products;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  insert into public.products (
    name, price, image_url, description, category
  )
  values (
    trim(p_name),
    p_price,
    coalesce(p_image_url, ''),
    coalesce(p_description, ''),
    coalesce(nullif(trim(p_category), ''), 'All')
  )
  returning * into v_row;

  perform public.seed_default_product_variant_stocks(v_row.id, 20);

  return v_row;
end;
$$;

create or replace function public.rpc_admin_update_product(
  p_product_id uuid,
  p_name text,
  p_price numeric,
  p_image_url text default '',
  p_description text default '',
  p_category text default 'All'
)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.products;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  update public.products
  set
    name = trim(p_name),
    price = p_price,
    image_url = coalesce(p_image_url, ''),
    description = coalesce(p_description, ''),
    category = coalesce(nullif(trim(p_category), ''), 'All')
  where id = p_product_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Product not found';
  end if;

  return v_row;
end;
$$;

create or replace function public.rpc_admin_delete_product(
  p_product_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  delete from public.products where id = p_product_id;
  get diagnostics v_deleted = row_count;
  return v_deleted > 0;
end;
$$;

create or replace function public.rpc_admin_get_product_variant_stocks(
  p_product_id uuid
)
returns table (
  size text,
  color text,
  stock int
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  return query
  select
    s.size,
    s.color,
    s.stock
  from public.product_variant_stocks s
  where s.product_id = p_product_id
  order by s.size, s.color;
end;
$$;

create or replace function public.rpc_admin_set_product_variant_stocks(
  p_product_id uuid,
  p_items jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int := 0;
  v_item jsonb;
  v_size text;
  v_color text;
  v_stock int;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'p_items must be a json array';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_size := trim(coalesce(v_item->>'size', ''));
    v_color := trim(coalesce(v_item->>'color', ''));
    v_stock := greatest(coalesce((v_item->>'stock')::int, 0), 0);

    if v_size <> '' and v_color <> '' then
      insert into public.product_variant_stocks (
        product_id, size, color, stock
      )
      values (
        p_product_id, v_size, v_color, v_stock
      )
      on conflict (product_id, size, color) do update
        set stock = excluded.stock,
            updated_at = now();

      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;

create or replace function public.rpc_admin_list_profiles()
returns table (
  id uuid,
  email text,
  name text,
  phone text,
  address text,
  account_type text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  return query
  select
    p.id,
    u.email::text,
    p.name::text,
    p.phone::text,
    p.address::text,
    p.account_type::text,
    p.created_at::timestamptz,
    p.updated_at::timestamptz
  from public.profiles p
  left join auth.users u on u.id = p.id
  order by p.created_at desc;
end;
$$;

drop function if exists public.rpc_admin_list_orders();

create or replace function public.rpc_admin_list_orders()
returns table (
  id bigint,
  user_id uuid,
  email text,
  total numeric,
  address text,
  address_details text,
  delivery_type text,
  payment_method text,
  cash_paid_confirmed boolean,
  cash_paid_confirmed_at timestamptz,
  cash_paid_confirmed_by uuid,
  payment_reference text,
  delivery_latitude double precision,
  delivery_longitude double precision,
  delivery_location_updated_at timestamptz,
  delivery_location_updated_by uuid,
  delivery_location_note text,
  status text,
  items jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_staff(auth.uid()) then
    raise exception 'Staff only';
  end if;

  return query
  select
    o.id::bigint,
    o.user_id::uuid,
    coalesce(u.email, '')::text,
    o.total::numeric,
    o.address::text,
    o.address_details::text,
    o.delivery_type::text,
    o.payment_method::text,
    o.cash_paid_confirmed::boolean,
    o.cash_paid_confirmed_at::timestamptz,
    o.cash_paid_confirmed_by::uuid,
    o.payment_reference::text,
    o.delivery_latitude::double precision,
    o.delivery_longitude::double precision,
    o.delivery_location_updated_at::timestamptz,
    o.delivery_location_updated_by::uuid,
    o.delivery_location_note::text,
    o.status::text,
    o.items::jsonb,
    o.created_at::timestamptz
  from public.orders o
  left join auth.users u on u.id = o.user_id
  order by o.created_at desc;
end;
$$;

create or replace function public.rpc_admin_set_account_type(
  p_user_id uuid,
  p_account_type text
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := lower(trim(coalesce(p_account_type, '')));
  v_row public.profiles;
begin
  if not public.is_super_admin(auth.uid()) then
    raise exception 'Super admin only';
  end if;

  if p_user_id is null then
    raise exception 'User id is required';
  end if;

  if p_user_id = auth.uid() and v_role <> 'super_admin' then
    raise exception 'Cannot change your own super admin role';
  end if;

  if v_role not in (
    'customer',
    'support_agent',
    'rider',
    'delivery',
    'cashier',
    'admin',
    'super_admin'
  ) then
    raise exception 'Invalid account type';
  end if;

  insert into public.profiles (
    id,
    account_type
  )
  values (
    p_user_id,
    v_role
  )
  on conflict (id) do update
    set account_type = excluded.account_type
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.rpc_admin_confirm_cash_payment(
  p_order_id bigint
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  if not (public.is_admin(auth.uid()) or public.is_cashier(auth.uid())) then
    raise exception 'Admin or cashier only';
  end if;

  select *
  into v_order
  from public.orders o
  where o.id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;

  if v_order.payment_method <> 'cash_on_delivery' then
    raise exception 'Order is not Cash on Delivery';
  end if;

  if v_order.status = 'cancelled' then
    raise exception 'Cancelled order cannot be confirmed';
  end if;

  if v_order.cash_paid_confirmed then
    return v_order;
  end if;

  update public.orders o
  set
    cash_paid_confirmed = true,
    cash_paid_confirmed_at = now(),
    cash_paid_confirmed_by = auth.uid(),
    status = case
      when lower(trim(coalesce(o.status, ''))) in ('pending', 'paid') then 'order_received'
      else o.status
    end
  where o.id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

create or replace function public.rpc_staff_update_order_status(
  p_order_id bigint,
  p_status text
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text := lower(trim(coalesce(p_status, '')));
  v_order public.orders;
  v_current_status text;
begin
  if not public.is_staff(auth.uid()) then
    raise exception 'Staff only';
  end if;

  if p_order_id is null then
    raise exception 'Order id is required';
  end if;

  if v_status in ('pending', 'paid') then
    v_status := 'order_received';
  elsif v_status = 'shipped' then
    v_status := 'out_for_delivery';
  end if;

  if v_status not in (
    'order_received',
    'order_packed',
    'ready_for_pickup',
    'out_for_delivery',
    'delivered',
    'cancelled'
  ) then
    raise exception 'Invalid status';
  end if;

  if public.is_rider(auth.uid()) and not public.is_admin(auth.uid())
    and v_status not in ('out_for_delivery', 'delivered') then
    raise exception 'Rider can update only out_for_delivery or delivered';
  end if;

  select *
  into v_order
  from public.orders o
  where o.id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;

  if v_order.status = 'cancelled' then
    raise exception 'Cancelled order cannot be updated';
  end if;

  v_current_status := lower(trim(coalesce(v_order.status, '')));
  if v_current_status in ('pending', 'paid') then
    v_current_status := 'order_received';
  elsif v_current_status = 'shipped' then
    v_current_status := 'out_for_delivery';
  end if;

  if public.is_rider(auth.uid()) and not public.is_admin(auth.uid()) then
    if v_status = 'out_for_delivery' and v_current_status not in ('order_received', 'order_packed') then
      raise exception 'Rider can mark out_for_delivery only from order_received or order_packed';
    end if;
    if v_status = 'delivered' and v_current_status not in ('out_for_delivery', 'ready_for_pickup') then
      raise exception 'Rider can mark delivered only after out_for_delivery or ready_for_pickup';
    end if;
  end if;

  if v_current_status = v_status then
    return v_order;
  end if;

  update public.orders o
  set status = v_status
  where o.id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

drop function if exists public.rpc_staff_list_support_requests();

create or replace function public.rpc_staff_list_support_requests()
returns table (
  id bigint,
  request_type text,
  message text,
  session_id text,
  is_anonymous boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (public.is_admin(auth.uid()) or public.is_support_agent(auth.uid())) then
    raise exception 'Admin or support agent only';
  end if;

  return query
  select
    l.id::bigint,
    coalesce(l.metadata->>'request_type', 'general')::text,
    l.message::text,
    coalesce(
      nullif(trim(coalesce(l.metadata->>'session_id', '')), ''),
      format('chat-%s', l.id::text)
    )::text,
    case
      when lower(coalesce(l.metadata->>'anonymous', '')) in ('false', 'f', '0', 'no') then false
      else true
    end,
    l.created_at::timestamptz
  from public.app_logs l
  where lower(l.feature) = 'customer_support'
    and lower(l.action) = 'request_submitted'
  order by l.created_at desc;
end;
$$;

create or replace function public.rpc_staff_update_order_delivery_location(
  p_order_id bigint,
  p_latitude double precision,
  p_longitude double precision,
  p_note text default ''
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_note text := trim(coalesce(p_note, ''));
  v_now timestamptz := now();
begin
  if not (public.is_admin(auth.uid()) or public.is_rider(auth.uid())) then
    raise exception 'Admin or rider only';
  end if;

  if p_order_id is null then
    raise exception 'Order id is required';
  end if;
  if p_latitude is null or p_longitude is null then
    raise exception 'Latitude and longitude are required';
  end if;
  if p_latitude < -90 or p_latitude > 90 then
    raise exception 'Latitude out of range';
  end if;
  if p_longitude < -180 or p_longitude > 180 then
    raise exception 'Longitude out of range';
  end if;

  select *
  into v_order
  from public.orders o
  where o.id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;

  if v_order.status = 'cancelled' then
    raise exception 'Cancelled order cannot be tracked';
  end if;

  if v_order.delivery_location_updated_at is not null
    and v_now < (v_order.delivery_location_updated_at + interval '5 seconds') then
    raise exception 'Too many location updates. Try again in a few seconds';
  end if;

  update public.orders o
  set
    delivery_latitude = p_latitude,
    delivery_longitude = p_longitude,
    delivery_location_updated_at = v_now,
    delivery_location_updated_by = auth.uid(),
    delivery_location_note = v_note
  where o.id = p_order_id
  returning * into v_order;

  insert into public.app_logs (
    level,
    feature,
    action,
    message,
    metadata,
    user_id
  )
  values (
    'info',
    'delivery_tracking',
    'location_updated',
    format('Updated delivery location for order #%s', p_order_id),
    jsonb_build_object(
      'order_id', p_order_id,
      'latitude', p_latitude,
      'longitude', p_longitude,
      'note', v_note,
      'status', v_order.status
    ),
    auth.uid()
  );

  return v_order;
end;
$$;

create or replace function public.rpc_get_active_event()
returns public.events
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_row public.events;
begin
  select *
  into v_row
  from public.events e
  where e.is_active = true
    and coalesce(e.starts_at, e.created_at, now()) <= now()
    and e.expires_at > now()
  order by
    e.expires_at asc,
    coalesce(e.starts_at, e.created_at, now()) desc,
    e.updated_at desc
  limit 1;

  return v_row;
end;
$$;

create or replace function public.rpc_app_log(
  p_level text default 'info',
  p_feature text default 'app',
  p_action text default 'event',
  p_message text default '',
  p_metadata jsonb default '{}'::jsonb,
  p_user_id uuid default auth.uid()
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_log_id bigint;
  v_level text := lower(coalesce(trim(p_level), 'info'));
begin
  if v_level not in ('info', 'warning', 'error') then
    v_level := 'info';
  end if;

  insert into public.app_logs (
    level,
    feature,
    action,
    message,
    metadata,
    user_id
  )
  values (
    v_level,
    coalesce(nullif(trim(p_feature), ''), 'app'),
    coalesce(nullif(trim(p_action), ''), 'event'),
    coalesce(p_message, ''),
    coalesce(p_metadata, '{}'::jsonb),
    p_user_id
  )
  returning id into v_log_id;

  return v_log_id;
end;
$$;

create or replace function public.rpc_upsert_payway_transaction(
  p_tran_id text,
  p_order_id bigint default null,
  p_amount numeric default null,
  p_currency text default 'USD',
  p_check_response jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_txn_id bigint;
  v_status text := upper(
    coalesce(
      nullif(trim(coalesce(
        p_check_response -> 'data' ->> 'payment_status',
        p_check_response ->> 'payment_status'
      )), ''),
      ''
    )
  );
  v_status_code int := null;
  v_gateway_code text := coalesce(
    nullif(trim(coalesce(
      p_check_response -> 'status' ->> 'code',
      p_check_response -> 'data' -> 'status' ->> 'code',
      p_check_response ->> 'code'
    )), ''),
    ''
  );
  v_gateway_message text := coalesce(
    nullif(trim(coalesce(
      p_check_response -> 'status' ->> 'message',
      p_check_response -> 'data' -> 'status' ->> 'message',
      p_check_response ->> 'message'
    )), ''),
    ''
  );
  v_currency text := upper(coalesce(nullif(trim(p_currency), ''), 'USD'));
  v_amount numeric(10, 2) := coalesce(p_amount, 0)::numeric(10, 2);
  v_status_code_text text := coalesce(
    nullif(trim(coalesce(
      p_check_response -> 'data' ->> 'payment_status_code',
      p_check_response ->> 'payment_status_code'
    )), ''),
    ''
  );
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if coalesce(trim(p_tran_id), '') = '' then
    raise exception 'tran_id is required';
  end if;

  if v_status_code_text ~ '^-?[0-9]+$' then
    v_status_code := v_status_code_text::int;
  end if;

  insert into public.payway_transactions (
    user_id,
    order_id,
    provider,
    tran_id,
    amount,
    currency,
    payment_status,
    payment_status_code,
    gateway_status_code,
    gateway_message,
    raw_response
  )
  values (
    v_user,
    p_order_id,
    'payway',
    trim(p_tran_id),
    v_amount,
    v_currency,
    v_status,
    v_status_code,
    v_gateway_code,
    v_gateway_message,
    coalesce(p_check_response, '{}'::jsonb)
  )
  on conflict (provider, tran_id)
  do update
    set
      user_id = excluded.user_id,
      order_id = coalesce(excluded.order_id, public.payway_transactions.order_id),
      amount = excluded.amount,
      currency = excluded.currency,
      payment_status = case
        when excluded.payment_status = '' then public.payway_transactions.payment_status
        else excluded.payment_status
      end,
      payment_status_code = coalesce(
        excluded.payment_status_code,
        public.payway_transactions.payment_status_code
      ),
      gateway_status_code = case
        when excluded.gateway_status_code = '' then public.payway_transactions.gateway_status_code
        else excluded.gateway_status_code
      end,
      gateway_message = case
        when excluded.gateway_message = '' then public.payway_transactions.gateway_message
        else excluded.gateway_message
      end,
      raw_response = case
        when excluded.raw_response = '{}'::jsonb then public.payway_transactions.raw_response
        else excluded.raw_response
      end,
      updated_at = now()
  returning id into v_txn_id;

  return v_txn_id;
end;
$$;

create or replace function public.rpc_admin_list_events()
returns setof public.events
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  return query
  select e.*
  from public.events e
  order by
    e.is_active desc,
    e.starts_at asc,
    e.expires_at asc,
    e.created_at desc;
end;
$$;

drop function if exists public.rpc_admin_create_event(text, text, text, boolean);
drop function if exists public.rpc_admin_create_event(text, text, text, boolean, timestamptz);
create or replace function public.rpc_admin_create_event(
  p_title text,
  p_subtitle text default '',
  p_badge text default '',
  p_is_active boolean default false,
  p_starts_at timestamptz default null,
  p_expires_at timestamptz default null,
  p_theme text default 'default'
)
returns public.events
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.events;
  v_now timestamptz := now();
  v_starts timestamptz := coalesce(p_starts_at, v_now);
  v_expires timestamptz := coalesce(p_expires_at, v_starts + interval '24 hours');
  v_theme text := lower(trim(coalesce(p_theme, 'default')));
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Title is required';
  end if;

  if v_theme = '' then
    v_theme := 'default';
  end if;

  if v_theme not in (
    'default',
    'christmas_sale',
    'valentine',
    'new_year',
    'black_friday',
    'summer_sale'
  ) then
    raise exception 'Invalid event theme';
  end if;

  if v_expires <= v_starts then
    raise exception 'Event end must be after start';
  end if;

  if coalesce(p_is_active, false) and v_expires <= v_now then
    raise exception 'Active event must end in the future';
  end if;

  if coalesce(p_is_active, false) then
    update public.events set is_active = false where is_active = true;
  end if;

  insert into public.events (
    title,
    subtitle,
    badge,
    is_active,
    starts_at,
    expires_at,
    theme
  )
  values (
    trim(p_title),
    coalesce(p_subtitle, ''),
    coalesce(p_badge, ''),
    coalesce(p_is_active, false),
    v_starts,
    v_expires,
    v_theme
  )
  returning * into v_row;

  return v_row;
end;
$$;

drop function if exists public.rpc_admin_update_event(uuid, text, text, text, boolean);
drop function if exists public.rpc_admin_update_event(uuid, text, text, text, boolean, timestamptz);
create or replace function public.rpc_admin_update_event(
  p_event_id uuid,
  p_title text,
  p_subtitle text default '',
  p_badge text default '',
  p_is_active boolean default false,
  p_starts_at timestamptz default null,
  p_expires_at timestamptz default null,
  p_theme text default null
)
returns public.events
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.events;
  v_now timestamptz := now();
  v_existing_starts timestamptz;
  v_existing_expiry timestamptz;
  v_existing_theme text;
  v_starts timestamptz;
  v_expires timestamptz;
  v_theme text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Title is required';
  end if;

  select
    e.starts_at,
    e.expires_at,
    e.theme
  into
    v_existing_starts,
    v_existing_expiry,
    v_existing_theme
  from public.events e
  where e.id = p_event_id;

  if v_existing_expiry is null or v_existing_starts is null then
    raise exception 'Event not found';
  end if;

  v_starts := coalesce(p_starts_at, v_existing_starts);
  v_expires := coalesce(p_expires_at, v_existing_expiry);
  v_theme := lower(trim(coalesce(p_theme, v_existing_theme, 'default')));

  if v_theme = '' then
    v_theme := 'default';
  end if;

  if v_theme not in (
    'default',
    'christmas_sale',
    'valentine',
    'new_year',
    'black_friday',
    'summer_sale'
  ) then
    raise exception 'Invalid event theme';
  end if;

  if v_expires <= v_starts then
    raise exception 'Event end must be after start';
  end if;

  if coalesce(p_is_active, false) and v_expires <= v_now then
    raise exception 'Active event must end in the future';
  end if;

  if coalesce(p_is_active, false) then
    update public.events
    set is_active = false
    where is_active = true and id <> p_event_id;
  end if;

  update public.events
  set
    title = trim(p_title),
    subtitle = coalesce(p_subtitle, ''),
    badge = coalesce(p_badge, ''),
    is_active = coalesce(p_is_active, false),
    starts_at = v_starts,
    theme = v_theme,
    expires_at = v_expires
  where id = p_event_id
  returning * into v_row;

  if v_row.id is null then
    raise exception 'Event not found';
  end if;

  return v_row;
end;
$$;

create or replace function public.rpc_admin_delete_event(
  p_event_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin only';
  end if;

  delete from public.events where id = p_event_id;
  get diagnostics v_deleted = row_count;
  return v_deleted > 0;
end;
$$;

-- ===== Grants for RPC usage =====

grant execute on function public.rpc_upsert_profile(text, text, text, boolean) to authenticated;
grant execute on function public.rpc_get_profile() to authenticated;
grant execute on function public.rpc_list_products(text, text) to anon, authenticated;
grant execute on function public.rpc_list_best_seller_product_ids(int, int) to anon, authenticated;
grant execute on function public.rpc_get_product_variant_stocks(uuid) to anon, authenticated;
grant execute on function public.rpc_get_cart_items() to authenticated;
grant execute on function public.rpc_add_to_cart(text, text, numeric, text, text, text, int) to authenticated;
grant execute on function public.rpc_set_cart_qty(text, int) to authenticated;
grant execute on function public.rpc_clear_cart() to authenticated;
grant execute on function public.rpc_get_wishlist_ids() to authenticated;
grant execute on function public.rpc_toggle_wishlist(text) to authenticated;
grant execute on function public.rpc_cart_total() to authenticated;
grant execute on function public.rpc_validate_promo_code(text) to authenticated;
grant execute on function public.rpc_place_order(text, text, text, text, text, text, text) to authenticated;
grant execute on function public.rpc_get_orders() to authenticated;
grant execute on function public.rpc_upsert_payway_transaction(text, bigint, numeric, text, jsonb) to authenticated;
grant execute on function public.rpc_get_active_event() to anon, authenticated;
grant execute on function public.rpc_app_log(text, text, text, text, jsonb, uuid) to anon, authenticated;
revoke all on function public.rpc_admin_create_product(text, numeric, text, text, text) from public;
grant execute on function public.rpc_admin_create_product(text, numeric, text, text, text) to authenticated;
revoke all on function public.rpc_admin_update_product(uuid, text, numeric, text, text, text) from public;
grant execute on function public.rpc_admin_update_product(uuid, text, numeric, text, text, text) to authenticated;
revoke all on function public.rpc_admin_delete_product(uuid) from public;
grant execute on function public.rpc_admin_delete_product(uuid) to authenticated;
revoke all on function public.rpc_admin_get_product_variant_stocks(uuid) from public;
grant execute on function public.rpc_admin_get_product_variant_stocks(uuid) to authenticated;
revoke all on function public.rpc_admin_set_product_variant_stocks(uuid, jsonb) from public;
grant execute on function public.rpc_admin_set_product_variant_stocks(uuid, jsonb) to authenticated;
revoke all on function public.rpc_admin_list_profiles() from public;
grant execute on function public.rpc_admin_list_profiles() to authenticated;
revoke all on function public.rpc_admin_list_orders() from public;
grant execute on function public.rpc_admin_list_orders() to authenticated;
revoke all on function public.rpc_admin_set_account_type(uuid, text) from public;
grant execute on function public.rpc_admin_set_account_type(uuid, text) to authenticated;
revoke all on function public.rpc_admin_confirm_cash_payment(bigint) from public;
grant execute on function public.rpc_admin_confirm_cash_payment(bigint) to authenticated;
revoke all on function public.rpc_staff_update_order_status(bigint, text) from public;
grant execute on function public.rpc_staff_update_order_status(bigint, text) to authenticated;
revoke all on function public.rpc_staff_list_support_requests() from public;
grant execute on function public.rpc_staff_list_support_requests() to authenticated;
revoke all on function public.rpc_staff_update_order_delivery_location(bigint, double precision, double precision, text) from public;
grant execute on function public.rpc_staff_update_order_delivery_location(bigint, double precision, double precision, text) to authenticated;
revoke all on function public.rpc_admin_list_events() from public;
grant execute on function public.rpc_admin_list_events() to authenticated;
revoke all on function public.rpc_admin_create_event(text, text, text, boolean, timestamptz, timestamptz, text) from public;
grant execute on function public.rpc_admin_create_event(text, text, text, boolean, timestamptz, timestamptz, text) to authenticated;
revoke all on function public.rpc_admin_update_event(uuid, text, text, text, boolean, timestamptz, timestamptz, text) from public;
grant execute on function public.rpc_admin_update_event(uuid, text, text, text, boolean, timestamptz, timestamptz, text) to authenticated;
revoke all on function public.rpc_admin_delete_event(uuid) from public;
grant execute on function public.rpc_admin_delete_event(uuid) to authenticated;
